CREATE TABLE IF NOT EXISTS `ALBUMS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `TITLE` varchar(128) NOT NULL DEFAULT '' COMMENT 'title',
  `ARTIST` varchar(128) NOT NULL DEFAULT '' COMMENT 'artist',
  `PRICE` float(11) NOT NULL DEFAULT 0 COMMENT 'price',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='albums';